# -----------------------------------------------------------------------------
# Configuration file for http://travis-ci.org/elasticsearch/elasticsearch-rails
# -----------------------------------------------------------------------------

language: node_js

node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"

python:
  - "2.7"

install: 
  - npm install intern --save-dev
  - sudo pip install python-bond selenium nose

test:
  - ~/node_modules/.bin/intern-client config=tests/intern
  - npm test
